- name: install Docker
  hosts: all
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - curl
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: latest
        update_cache: true
    
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
        
    - name: adding ubuntu to docker group
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: "Create .ssh dir"
      ansible.builtin.file:
        path: ".ssh"
        state: directory
        owner: "{{ user_name }}"

    - name: generate SSH key id_rsa
      become: no
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no
    
    - name: "Read a ssh file content"
      shell: |
        cat ~/.ssh/id_rsa.pub
      register: file_content
      become: no

    - name: "Print ssh key"
      debug:
        msg: "{{ file_content.stdout }}"
