name: Validate VERSION File

on:
  pull_request:
    paths:
      - 'VERSION'

jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Validate that the VERSION file is updated
      - name: Check VERSION file update
        run: |
          BASE_BRANCH=$(jq -r .base.ref < "$GITHUB_EVENT_PATH")
          if git diff --name-only origin/$BASE_BRANCH...HEAD | grep -q "^VERSION$"; then
            echo "VERSION file has been updated."
          else
            echo "Error: VERSION file was not updated." >&2
            exit 1
          fi

      # Validate the format of the VERSION file
      - name: Validate VERSION format
        run: |
          if ! grep -Eq "^v[0-9]+\.[0-9]+\.[0-9]+$" VERSION; then
            echo "Error: VERSION file must contain a valid semantic version (e.g., v1.0.0)." >&2
            exit 1
          fi
