name: Validate VERSION File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Validate that the VERSION file is updated
      - name: Check VERSION file update
        run: |
          if git diff --name-only origin/main...HEAD | grep -q "^VERSION$"; then
            echo "VERSION file has been updated."
          else
            echo "Error: VERSION file was not updated." >&2
            exit 1
          fi
